import './globals.css'
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Social BTW',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <div align='center'>
          <br />
          <div className="personal-hiscores__table">
            <div id="col2">
              <div id="headerHiscores"></div>
              <div className="hiscoresHiddenBG">
                <div id="contentHiscores">
                  {children}
                </div>
              </div>
              <div id="footerHiscores"></div>
            </div>
          </div>
        </div>
      </body>
    </html>
  )
}
