import './globals.css'
import type { Metadata } from 'next'
import styles from '@/styles/hiscores.module.css'
import { runescapeChat07 } from './fonts/fonts'

export const metadata: Metadata = {
  title: 'Social BTW',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <main className={runescapeChat07.className}>
          <div className={styles.hiscoresHeader} />
          <div className={styles.hiscoresContent}>
            {children}
          </div>
          <div className={styles.hiscoresFooter} />
        </main>
      </body>
    </html>
  )
}
